import { useState } from 'react'
import { BarChart3, CircleDollarSign, Receipt, Wallet } from 'lucide-react'
import { calculateComparison, filterTransactions } from '../utils/calculationUtils'
import { getCurrentYear, getNow, toStorageDate } from '../utils/dateUtils'
import { money } from '../utils/currencyUtils'
import { Stat } from './Dashboard'

const yearStart = () => toStorageDate(new Date(getNow().getFullYear(), 0, 1))
const today = () => toStorageDate(getNow())
export default function Comparison({ transactions, categories }) { const [a, setA] = useState({ start: yearStart(), end: today() }), [b, setB] = useState({ start: `${getCurrentYear() - 1}-01-01`, end: `${getCurrentYear() - 1}-12-31` }), [categoryId, setCategoryId] = useState(''); const scoped = list => categoryId ? list.filter(x => x.categoryId === Number(categoryId)) : list; const periodA = scoped(filterTransactions(transactions, { startDate: a.start, endDate: a.end })), periodB = scoped(filterTransactions(transactions, { startDate: b.start, endDate: b.end })), result = calculateComparison(periodB, periodA); return <><div className="page-intro"><div><div className="eyebrow">Period A compared with Period B</div><h2>Period comparison</h2><p>Compare any two calendar ranges without copying transactions.</p></div></div><section className="card comparison-form"><div><label>Period A start<input type="date" value={a.start} onChange={e => setA({ ...a, start: e.target.value })} /></label><label>Period A end<input type="date" value={a.end} onChange={e => setA({ ...a, end: e.target.value })} /></label></div><div><label>Period B start<input type="date" value={b.start} onChange={e => setB({ ...b, start: e.target.value })} /></label><label>Period B end<input type="date" value={b.end} onChange={e => setB({ ...b, end: e.target.value })} /></label></div><label>Category<select value={categoryId} onChange={e => setCategoryId(e.target.value)}><option value="">All categories</option>{categories.filter(x => x.type === 'expense').map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label></section><div className="stat-grid"><Stat label="Income change" value={`${money(result.incomeDiff)} (${result.incomeChange.toFixed(1)}%)`} tone={result.incomeDiff >= 0 ? 'income' : 'expense'} icon={CircleDollarSign} /><Stat label="Expense change" value={`${money(result.expenseDiff)} (${result.expenseChange.toFixed(1)}%)`} tone={result.expenseDiff <= 0 ? 'income' : 'expense'} icon={Wallet} /><Stat label="Net income change" value={`${money(result.netDiff)} (${result.netChange.toFixed(1)}%)`} tone={result.netDiff >= 0 ? 'income' : 'expense'} icon={BarChart3} /><Stat label="Records compared" value={`${periodA.length} vs ${periodB.length}`} tone="neutral" icon={Receipt} /></div><section className="card comparison-table"><table><thead><tr><th>Metric</th><th>Period A</th><th>Period B</th><th>Difference</th></tr></thead><tbody><tr><td>Total income</td><td>{money(result.periodB.totalIncome)}</td><td>{money(result.periodA.totalIncome)}</td><td>{money(result.incomeDiff)}</td></tr><tr><td>Total expenses</td><td>{money(result.periodB.totalExpenses)}</td><td>{money(result.periodA.totalExpenses)}</td><td>{money(result.expenseDiff)}</td></tr><tr><td>Net income</td><td>{money(result.periodB.netIncome)}</td><td>{money(result.periodA.netIncome)}</td><td>{money(result.netDiff)}</td></tr></tbody></table></section></> }
