import { BarChart3, CircleDollarSign, Wallet, Receipt, Plus } from 'lucide-react'
import { Cell, CartesianGrid, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { getCurrentMonthName, getCurrentYear } from '../utils/dateUtils'
import { money } from '../utils/currencyUtils'

export function Stat({ label, value, tone, icon: Icon }) { return <div className={`stat card ${tone}`}><div className="stat-icon"><Icon size={19} /></div><div><span>{label}</span><strong>{value}</strong></div></div> }
export function Empty() { return <div className="empty"><Receipt size={27} /><strong>No records match these filters</strong><span>Clear filters or add a transaction.</span></div> }
export default function Dashboard({ totals, months, categories, onNewExpense = () => window.dispatchEvent(new CustomEvent('hotel:new-transaction', { detail: { type: 'expense' } })), onNewIncome = () => window.dispatchEvent(new CustomEvent('hotel:new-transaction', { detail: { type: 'income' } })) }) {
  return <><div className="page-intro"><div><div className="eyebrow">Live ledger • {getCurrentMonthName()} {getCurrentYear()}</div><h2>Financial picture</h2><p>Every figure below is calculated from the same stored transaction records.</p></div><div className="button-row"><button className="button secondary" onClick={onNewIncome}><Plus size={15} /> New income</button><button className="button primary" onClick={onNewExpense}><Plus size={15} /> New expense</button></div></div>
    <div className="stat-grid"><Stat label="Total income" value={money(totals.totalIncome)} tone="income" icon={CircleDollarSign} /><Stat label="Total expenses" value={money(totals.totalExpenses)} tone="expense" icon={Wallet} /><Stat label="Net income" value={money(totals.netIncome)} tone={totals.netIncome >= 0 ? 'income' : 'expense'} icon={BarChart3} /><Stat label="Transactions" value={totals.transactionCount} tone="neutral" icon={Receipt} /></div>
    <div className="chart-grid"><section className="card chart-card wide"><h3>Income vs expenses</h3><p>Monthly movement for active filters</p><ResponsiveContainer width="100%" height={280}><LineChart data={months}><CartesianGrid strokeDasharray="3 3" stroke="#dfe7e5" /><XAxis dataKey="name" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip formatter={v => money(v)} /><Legend /><Line dataKey="income" stroke="#1f5946" strokeWidth={3} dot={false} /><Line dataKey="expenses" stroke="#3e6b52" strokeWidth={3} dot={false} /><Line dataKey="net" stroke="#9aae91" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer></section>
      <section className="card chart-card"><h3>Expense mix</h3><p>By category</p>{categories.length ? <ResponsiveContainer width="100%" height={280}><PieChart><Pie data={categories} dataKey="value" nameKey="name" innerRadius={58} outerRadius={94}>{categories.map((_, i) => <Cell key={i} fill={['#e05a47', '#f08a3c', '#d3a32f', '#7b61a8', '#2f80a9', '#319b78', '#d05b8b', '#65717b'][i % 8]} />)}</Pie><Tooltip formatter={v => money(v)} /><Legend /></PieChart></ResponsiveContainer> : <Empty />}</section></div>
  </>
}
