import { useState } from 'react'
import { CheckCircle2, Receipt } from 'lucide-react'
import toast from 'react-hot-toast'
import { getNow, toStorageDate } from '../utils/dateUtils'

const initial = type => ({ type, date: toStorageDate(getNow()), description: '', reference: '', supplier: '', categoryId: '', departmentId: '', paymentMethodId: '', amount: '', notes: '' })

export default function ManualEntry({ categories, methods, departments, onSave }) {
  const [type, setType] = useState('expense')
  const [form, setForm] = useState(initial('expense'))
  const updateType = nextType => { setType(nextType); setForm(initial(nextType)) }
  const update = (key, value) => setForm(current => ({ ...current, [key]: value }))
  const submit = async event => { event.preventDefault(); if (!form.date || !form.description || !form.categoryId || !form.paymentMethodId || Number(form.amount) <= 0) { toast.error('Complete date, description, category, payment method, and amount.'); return } await onSave({ ...form, date: toStorageDate(form.date), amount: Number(form.amount), categoryId: Number(form.categoryId), paymentMethodId: Number(form.paymentMethodId), departmentId: form.departmentId ? Number(form.departmentId) : undefined }); setForm(initial(type)); toast.success('Transaction saved and connected to all reports') }
  const activeCategories = Array.from(new Map(categories.filter(item => item.isActive && item.type === type).map(item => [item.name.toLowerCase().trim(), item])).values())
  const activeMethods = Array.from(new Map(methods.filter(item => item.isActive).map(item => [item.name.toLowerCase().trim(), item])).values())
  const activeDepartments = Array.from(new Map(departments.filter(item => item.isActive).map(item => [item.name.toLowerCase().trim(), item])).values())
  return <><div className="page-intro"><div><div className="eyebrow">Encode once, organize automatically</div><h2>Manual entry</h2><p>Enter the transaction once. The system assigns its date, month, year, category, and payment method across every report.</p></div></div><section className="manual-entry-layout"><div className="card manual-entry-card"><div className="entry-type"><button className={type === 'expense' ? 'selected' : ''} onClick={() => updateType('expense')}><Receipt size={17} /> Expense</button><button className={type === 'income' ? 'selected' : ''} onClick={() => updateType('income')}><CheckCircle2 size={17} /> Income</button></div><form onSubmit={submit}><div className="form-grid"><label>Date<input type="date" value={form.date} onChange={event => update('date', event.target.value)} required /></label><label>Amount<input type="number" min="0.01" step="0.01" value={form.amount} onChange={event => update('amount', event.target.value)} placeholder="0.00" required /></label><label className="span-2">Description<input value={form.description} onChange={event => update('description', event.target.value)} placeholder="What was this transaction for?" required /></label><label>Category<select value={form.categoryId} onChange={event => update('categoryId', event.target.value)} required><option value="">Select category</option>{activeCategories.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Payment method<select value={form.paymentMethodId} onChange={event => update('paymentMethodId', event.target.value)} required><option value="">Select payment method</option>{activeMethods.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Department<select value={form.departmentId} onChange={event => update('departmentId', event.target.value)}><option value="">Unassigned</option>{activeDepartments.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Receipt / reference<input value={form.reference} onChange={event => update('reference', event.target.value)} placeholder="Optional" /></label><label>Supplier / vendor<input value={form.supplier} onChange={event => update('supplier', event.target.value)} placeholder="Optional" /></label><label className="span-2">Notes<textarea value={form.notes} onChange={event => update('notes', event.target.value)} rows="3" /></label></div><button className="button primary manual-save" type="submit">Save {type}</button></form></div><div className="card entry-summary"><h3>After saving</h3><div><strong>One record</strong><span>Stored in the shared transaction ledger</span></div><div><strong>Automatic organization</strong><span>Month, year, category, department, and payment</span></div><div><strong>Automatic reporting</strong><span>Dashboard, charts, records, and income statement</span></div></div></section></>
}
