import { Plus, X } from 'lucide-react'

export default function TransactionModal({ form, setForm, save, categories, methods, departments, close }) {
  const update = (key, value) => setForm({ ...form, [key]: value })
  const unique = items => Array.from(new Map(items.map(item => [item.name.toLowerCase().trim(), item])).values())
  const visibleCategories = unique(categories)
  const visibleMethods = unique(methods)
  const visibleDepartments = unique(departments)
  const selectedCategory = visibleCategories.find(item => String(item.id) === String(form.categoryId))
  const subcategories = selectedCategory?.subcategories || []
  return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><div className="eyebrow">Expense entry</div><h2>{form.description ? 'Edit transaction' : 'New expense'}</h2></div><button className="icon-button" onClick={close} aria-label="Close"><X size={18} /></button></div><form onSubmit={save}><div className="form-grid"><label>Date<input type="date" value={form.date} onChange={event => update('date', event.target.value)} required /></label><label>Amount<input type="number" min="0.01" step="0.01" value={form.amount} onChange={event => update('amount', event.target.value)} required /></label><label className="span-2">Description<input value={form.description} onChange={event => update('description', event.target.value)} required /></label><label>Category<select value={form.categoryId} onChange={event => setForm({ ...form, categoryId: event.target.value, subcategory: '' })} required><option value="">Select category</option>{visibleCategories.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Sub-category<select value={form.subcategory || ''} onChange={event => update('subcategory', event.target.value)} disabled={!subcategories.length}><option value="">{subcategories.length ? 'Select sub-category' : 'General expense'}</option>{subcategories.map(item => <option key={item} value={item}>{item}</option>)}</select></label><label>Payment method<select value={form.paymentMethodId} onChange={event => update('paymentMethodId', event.target.value)} required><option value="">Select method</option>{visibleMethods.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Department<select value={form.departmentId || ''} onChange={event => update('departmentId', event.target.value)}><option value="">Unassigned</option>{visibleDepartments.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Receipt / reference<input value={form.reference || ''} onChange={event => update('reference', event.target.value)} /></label><label>Supplier / vendor<input value={form.supplier || ''} onChange={event => update('supplier', event.target.value)} /></label><label className="span-2">Notes<textarea value={form.notes || ''} onChange={event => update('notes', event.target.value)} rows="3" /></label></div><div className="modal-actions"><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button primary"><Plus size={16} /> Save expense</button></div></form></div></div>
}
